name: 🚀 Ultra Simple CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    name: 🧪 Ultra Simple Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Setup DB
        run: npm run setup

      - name: Test
        run: |
          npm start &
          sleep 20
          npm test
        env:
          CI: true

      - name: Results
        if: always()
        run: echo "Done"
